slug: lf-energy-standards-and-specifications
landscapeProjectsCategory: LFESS Working Groups
landscapeProjectsSubcategories:
  - name: Working Group
    category: Working Group
  - name: All
    category: Working Group
landscapeProjectsLevels:
  - level: working-group
    name: Working Group
landscapefile: landscape.yml
projectsDefaultCrunchbase: https://www.crunchbase.com/organization/lf-energy
memberSuffix: ' (member)'
tacAgendaProjectUrl: https://github.com/orgs/lf-energy/projects/2/views/2
artworkRepoUrl: "https://artwork.lfenergy.org/projects/{slug}"
