landscapeName: lfenergy
landscapeMemberClasses:
  - name: Strategic Membership
    category: Strategic
  - name: Premier Membership
    category: Strategic
  - name: General Membership
    category: General
  - name: Associate Membership
    category: Associate
project: a094100001Cb6HaAAJ # LF Energy Foundation
slug: lfenergy
landscapeMemberCategory: LF Energy Member
landscapeProjectsCategory: LF Energy Projects
landscapeProjectsSubcategories:
  - name: All
    category: All
landscapefile: landscape.yml
memberSuffix: ' (member)'
missingcsvfile: missing.csv
